version: '3.8'

services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: ${MONGO_URI}
      DB_NAME: ${DB_NAME}
      COLLECTION_NAME: ${COLLECTION_NAME}
    restart: always
